server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: demo:demo@tcp(127.0.0.1:3306)/demo?parseTime=true
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime : 600
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
