// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-crud/internal/biz"
	"kratos-crud/internal/conf"
	"kratos-crud/internal/data"
	"kratos-crud/internal/server"
	"kratos-crud/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userInfoRepoIf := data.NewUserInfoRepo(dataData, logger)
	userInfoUsecase := biz.NewUserInfoUsecase(userInfoRepoIf, logger)
	userInfoService := service.NewUserInfoService(userInfoUsecase)
	httpServer := server.NewHTTPServer(confServer, userInfoService, logger)
	grpcServer := server.NewGRPCServer(confServer, userInfoService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
